vim.lsp.enable("ts_ls")
vim.lsp.enable("lua_ls")
vim.lsp.enable("bashls")
vim.lsp.enable("cssls")
vim.lsp.enable("eslint")
vim.lsp.enable("gleam")
vim.lsp.enable("roslyn_ls")
vim.lsp.enable("html")
vim.lsp.enable("nginx_language_server")
vim.lsp.enable("sqls")
vim.lsp.enable("gopls")
vim.lsp.enable("jsonls")
vim.lsp.enable("marksman")
vim.lsp.enable("svelte")
vim.lsp.enable("terraformls")
vim.lsp.enable("zk")
vim.lsp.enable("nil_ls")
vim.lsp.enable("rust_analyzer")
vim.lsp.enable("emmet_language_server")
vim.lsp.enable("astro")
vim.lsp.enable("qmlls")
vim.lsp.enable("zls")
vim.lsp.enable("openscad_ls")

if vim.fn.executable("basedpyright") == 1 then
	vim.lsp.enable("basedpyright")
elseif vim.fn.executable("pyright") == 1 then
	vim.lsp.enable("pyright")
end
